name: Test Shiny App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: SETUP R using renv.lock version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: auto
      
      - name: SETUP R dependencies with renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Run tests
        run: |
          Rscript -e "shinytest2::test_app()"
      
      - name: Upload test results (fails)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: shiny-test-results
          path: tests/testthat
